## VSCode Extension: REST Client 
### Shorten a url
POST http://localhost:5000/shorten
content-type: application/json

{
    "url": "https://excalidraw.com/#json=KaBOwH7FMOeBjg4dO1sFV,Tl64CN9RVVSV0SeTEOoqDQ"
}

#### redirect_url
GET http://localhost:5000/q6IG1J