## VSCode Extension: REST Client 
### Create a book
POST http://127.0.0.1:8000/api/books/
content-type: application/json
# Authorization: Bearer <access_token>

{
    "title": "Time is Money",
    "author": "James",
    "remark": "remark...",
    "publication_date": "2024-11-21"
}


### GetList
GET http://127.0.0.1:8000/api/books/getList/

### Detail
GET http://127.0.0.1:8000/api/books/8/

### Update a book
PUT http://127.0.0.1:8000/api/books/update/8/
content-type: application/json

{
    "id": 8,
    "title": "88",
    "author": "88",
    "remark": "88",
    "publication_date": "2024-11-25"
}


### delete a book
DELETE http://127.0.0.1:8000/api/books/delete/6/
content-type: application/json

